// Generated by https://quicktype.io

export interface IProduct {
    product_detail:      string;
    brand:               string;
    sub_category:        string;
    product_discount:    string;
    product_price:       string;
    category:            string;
    product_image:       string;
    product_description: string;
    sub_sub_category:    string;
    product_name:        string;
    store:               string;
    id?: string;
}
