// Generated by https://quicktype.io

export interface IProduct {
    id?:                           string;
    brand:                         string;
    category:                      string;
    category_group:                string;
    model:                         string;
    model_store_unique_identifier: string;
    price_history:                 IPriceHistory[];
    product_description:           string;
    product_detail:                string;
    product_discount:              string;
    product_image:                 string;
    product_name:                  string;
    product_price:                 string;
    store:                         string;
    sub_category:                  string;
}

export interface IPriceHistory {
    fecha: string;
    price: string;
    priceRender: number;
}

export interface IFavoriteProduct {
    store?: string;
    category_group?: string;
    category?: string;
    sub_category?: string;
    model?: string;
  }
  