// Generated by https://quicktype.io

export interface IProduct {
  id?: string;
  brand: string;
  category: string;
  category_group: string;
  model: string;
  model_store_unique_identifier: string;
  price_history: IPriceHistory[];
  pricekey: string;
  product_description: string;
  product_detail: string;
  product_discount: string;
  product_image: string;
  product_name: string;
  product_price: string;
  store: string;
  sub_category: string;
  product_price_key: string; // for filters
  product_name_key: string;
  brand_key: string;
  category_key: string;
  sub_category_key: string;
}

export interface IPriceHistory {
  fecha: string;
  price: string;
  priceRender: number;
}

export interface IFavoriteProduct {
  model_store_unique_identifier?: string;
  category_group?: string;
  category?: string;
  sub_category?: string;
}

export type Filter = 'product_name_key' | 'brand_key' | 'sub_category_key' | 'product_price_key';
